#pragma once
#define XTC_PORT 1337
#define XTC_DISCOVERY_PORT 1338
#define XTC_FRONTEND_PORT 1339
#define XTSTATUS_OK 0
#define XTSTATUS_FAILED 1
#define XTSTATUS_INVALID_SYNTAX 2
#define XTSTATUS_BAD_REQUEST 3